--DROP TABLE TRADING_CALENDAR;

CREATE TABLE TRADING_CALENDAR
  (
    DATE_VALUE DATE NOT NULL ,
    IS_TRADING_DATE  VARCHAR2 (1 CHAR) NOT NULL ,
    MOD_TIMESTAMP TIMESTAMP DEFAULT systimestamp NOT NULL,
    CONSTRAINT TRADING_CALENDAR_PK PRIMARY KEY (DATE_VALUE)
  ) ;

--delete TRADING_CALENDAR;
Insert into TRADING_CALENDAR (DATE_VALUE,IS_TRADING_DATE,MOD_TIMESTAMP) values (to_date('25-DEC-2018','DD-MON-YYYY'),'N',to_timestamp('05-MAR-19 09.18.17.145688000','DD-MON-RR HH24.MI.SSXFF'));
Insert into TRADING_CALENDAR (DATE_VALUE,IS_TRADING_DATE,MOD_TIMESTAMP) values (to_date('26-DEC-2018','DD-MON-YYYY'),'N',to_timestamp('05-MAR-19 09.19.44.899494000','DD-MON-RR HH24.MI.SSXFF'));
Insert into TRADING_CALENDAR (DATE_VALUE,IS_TRADING_DATE,MOD_TIMESTAMP) values (to_date('01-JAN-2019','DD-MON-YYYY'),'N',to_timestamp('05-MAR-19 09.20.10.292707000','DD-MON-RR HH24.MI.SSXFF'));

Commit;
